/**
 * Snippet definitions for buttons and autocomplete dictionary.
 * Each entry: { name, description, snippet, cursorOffset }
 *   - snippet: text to insert (with $1 marking cursor position)
 *   - If no $1, cursor goes to end of inserted text
 */

const SNIPPETS = {
  bmatrix:  { text: '\\begin{bmatrix}  \\\\  \\end{bmatrix}', cursor: 16 },
  pmatrix:  { text: '\\begin{pmatrix}  \\\\  \\end{pmatrix}', cursor: 16 },
  vmatrix:  { text: '\\begin{vmatrix}  \\\\  \\end{vmatrix}', cursor: 16 },
  frac:     { text: '\\frac{}{}', cursor: 6 },
  sum:      { text: '\\sum_{i=}^{}', cursor: 7 },
  int:      { text: '\\int_{}^{}', cursor: 6 },
  cases:    { text: '\\begin{cases}  &  \\\\  &  \\end{cases}', cursor: 14 },
  aligned:  { text: '\\begin{aligned}  &=  \\\\  &=  \\end{aligned}', cursor: 16 },
  sqrt:     { text: '\\sqrt{}', cursor: 6 },
  hat:      { text: '\\hat{}', cursor: 5 },
  dot:      { text: '\\dot{}', cursor: 5 },
  ddot:     { text: '\\ddot{}', cursor: 6 },
};

// Autocomplete dictionary: ~100 LaTeX commands
const AUTOCOMPLETE_DICT = [
  // Greek letters (lowercase)
  { name: '\\alpha', desc: 'α' },
  { name: '\\beta', desc: 'β' },
  { name: '\\gamma', desc: 'γ' },
  { name: '\\delta', desc: 'δ' },
  { name: '\\epsilon', desc: 'ε' },
  { name: '\\varepsilon', desc: 'ε (var)' },
  { name: '\\zeta', desc: 'ζ' },
  { name: '\\eta', desc: 'η' },
  { name: '\\theta', desc: 'θ' },
  { name: '\\vartheta', desc: 'θ (var)' },
  { name: '\\iota', desc: 'ι' },
  { name: '\\kappa', desc: 'κ' },
  { name: '\\lambda', desc: 'λ' },
  { name: '\\mu', desc: 'μ' },
  { name: '\\nu', desc: 'ν' },
  { name: '\\xi', desc: 'ξ' },
  { name: '\\pi', desc: 'π' },
  { name: '\\rho', desc: 'ρ' },
  { name: '\\sigma', desc: 'σ' },
  { name: '\\tau', desc: 'τ' },
  { name: '\\upsilon', desc: 'υ' },
  { name: '\\phi', desc: 'φ' },
  { name: '\\varphi', desc: 'φ (var)' },
  { name: '\\chi', desc: 'χ' },
  { name: '\\psi', desc: 'ψ' },
  { name: '\\omega', desc: 'ω' },

  // Greek letters (uppercase)
  { name: '\\Gamma', desc: 'Γ' },
  { name: '\\Delta', desc: 'Δ' },
  { name: '\\Theta', desc: 'Θ' },
  { name: '\\Lambda', desc: 'Λ' },
  { name: '\\Xi', desc: 'Ξ' },
  { name: '\\Pi', desc: 'Π' },
  { name: '\\Sigma', desc: 'Σ' },
  { name: '\\Phi', desc: 'Φ' },
  { name: '\\Psi', desc: 'Ψ' },
  { name: '\\Omega', desc: 'Ω' },

  // Operators & relations
  { name: '\\times', desc: '×' },
  { name: '\\div', desc: '÷' },
  { name: '\\cdot', desc: '·' },
  { name: '\\pm', desc: '±' },
  { name: '\\mp', desc: '∓' },
  { name: '\\leq', desc: '≤' },
  { name: '\\geq', desc: '≥' },
  { name: '\\neq', desc: '≠' },
  { name: '\\approx', desc: '≈' },
  { name: '\\equiv', desc: '≡' },
  { name: '\\sim', desc: '∼' },
  { name: '\\propto', desc: '∝' },
  { name: '\\infty', desc: '∞' },
  { name: '\\partial', desc: '∂' },
  { name: '\\nabla', desc: '∇' },
  { name: '\\forall', desc: '∀' },
  { name: '\\exists', desc: '∃' },
  { name: '\\in', desc: '∈' },
  { name: '\\notin', desc: '∉' },
  { name: '\\subset', desc: '⊂' },
  { name: '\\supset', desc: '⊃' },
  { name: '\\cup', desc: '∪' },
  { name: '\\cap', desc: '∩' },
  { name: '\\emptyset', desc: '∅' },

  // Structures with snippets
  { name: '\\frac', desc: 'fraction', snippet: '\\frac{}{} ', cursorInSnippet: 6 },
  { name: '\\sqrt', desc: 'square root', snippet: '\\sqrt{}', cursorInSnippet: 6 },
  { name: '\\sum', desc: 'summation', snippet: '\\sum_{i=}^{}', cursorInSnippet: 7 },
  { name: '\\prod', desc: 'product', snippet: '\\prod_{i=}^{}', cursorInSnippet: 8 },
  { name: '\\int', desc: 'integral', snippet: '\\int_{}^{}', cursorInSnippet: 6 },
  { name: '\\iint', desc: 'double integral' },
  { name: '\\iiint', desc: 'triple integral' },
  { name: '\\oint', desc: 'contour integral' },
  { name: '\\lim', desc: 'limit', snippet: '\\lim_{\\to }', cursorInSnippet: 6 },
  { name: '\\begin', desc: 'environment', snippet: '\\begin{}\\end{}', cursorInSnippet: 7 },
  { name: '\\hat', desc: 'hat accent', snippet: '\\hat{}', cursorInSnippet: 5 },
  { name: '\\bar', desc: 'bar accent', snippet: '\\bar{}', cursorInSnippet: 5 },
  { name: '\\vec', desc: 'vector arrow', snippet: '\\vec{}', cursorInSnippet: 5 },
  { name: '\\dot', desc: 'dot accent', snippet: '\\dot{}', cursorInSnippet: 5 },
  { name: '\\ddot', desc: 'double dot', snippet: '\\ddot{}', cursorInSnippet: 6 },
  { name: '\\tilde', desc: 'tilde accent', snippet: '\\tilde{}', cursorInSnippet: 7 },
  { name: '\\overline', desc: 'overline', snippet: '\\overline{}', cursorInSnippet: 10 },
  { name: '\\underline', desc: 'underline', snippet: '\\underline{}', cursorInSnippet: 11 },
  { name: '\\overbrace', desc: 'overbrace', snippet: '\\overbrace{}', cursorInSnippet: 11 },
  { name: '\\underbrace', desc: 'underbrace', snippet: '\\underbrace{}', cursorInSnippet: 12 },
  { name: '\\mathbf', desc: 'bold', snippet: '\\mathbf{}', cursorInSnippet: 8 },
  { name: '\\mathbb', desc: 'blackboard bold', snippet: '\\mathbb{}', cursorInSnippet: 8 },
  { name: '\\mathcal', desc: 'calligraphic', snippet: '\\mathcal{}', cursorInSnippet: 9 },
  { name: '\\mathrm', desc: 'roman', snippet: '\\mathrm{}', cursorInSnippet: 8 },
  { name: '\\text', desc: 'text mode', snippet: '\\text{}', cursorInSnippet: 6 },

  // Arrows
  { name: '\\leftarrow', desc: '←' },
  { name: '\\rightarrow', desc: '→' },
  { name: '\\leftrightarrow', desc: '↔' },
  { name: '\\Leftarrow', desc: '⇐' },
  { name: '\\Rightarrow', desc: '⇒' },
  { name: '\\Leftrightarrow', desc: '⇔' },
  { name: '\\uparrow', desc: '↑' },
  { name: '\\downarrow', desc: '↓' },

  // Delimiters & misc
  { name: '\\left', desc: 'left delimiter' },
  { name: '\\right', desc: 'right delimiter' },
  { name: '\\bigl', desc: 'big left' },
  { name: '\\bigr', desc: 'big right' },
  { name: '\\ldots', desc: '…' },
  { name: '\\cdots', desc: '⋯' },
  { name: '\\vdots', desc: '⋮' },
  { name: '\\ddots', desc: '⋱' },
  { name: '\\quad', desc: 'quad space' },
  { name: '\\qquad', desc: 'double quad space' },
  { name: '\\hspace', desc: 'horizontal space' },
  { name: '\\displaystyle', desc: 'display style' },
  { name: '\\textstyle', desc: 'text style' },
];
